name: "vllm_model"
backend: "python"

input [
  {
    name: "PROMPT"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "COMPLETION"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
